version: '2'

services:
 php_server:
  container_name: php-sf
  build: ./php
  volumes:
   - ../:/var/www/html
  environment:
   - DATABASE_HOST
   - DATABASE_PORT
   - DATABASE_NAME
   - DATABASE_USER
   - DATABASE_PASSWORD
  links:
   - mysql_server
   - redis_server

 mysql_server:
  container_name: mysql-sf
  image: mysql:5.7
  environment:
   MYSQL_DATABASE: ${DATABASE_NAME}
   MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
   MYSQL_USER: ${DATABASE_USER}
   MYSQL_PASSWORD: ${DATABASE_PASSWORD}
  volumes:
   - /var/lib/mysql
  ports:
   - "3306:3306"

 redis_server:
   container_name: redis-sf
   image: redis:alpine
   ports:
    - "6379:6379"

 nginx_server:
  container_name: nginx-sf
  build: ./nginx
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ../:/usr/share/nginx/html
  links:
   - php_server
